version: '3'
services:
  winery:
    image: opentosca/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      EDMM_TRANSFORMATION_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_FEATURE_EDMM_MODELING: "true"
      WINERY_FEATURE_UPDATE_TEMPLATES: "true"
      WINERY_REPOSITORY_URL: "https://github.com/UST-EDMM/modeling-repository"
    ports:
      - '8080:8080'
    networks:
      - edmm
  edmm:
    image: ustedmm/edmm:latest
    ports:
      - '5000:5000'
    networks:
      - edmm
networks:
  edmm:
    driver: bridge
